### ISSUE TITLE
backgroud style misspelling

### ISSUE THREAD

**Issue by jphornor** [write2sv/ionic4-date-picker#1]
Great work on this! While running ng build --prod, I get this error: 

`ERROR in node_modules/ionic4-date-picker/dist/components/date-picker-component/date-picker-component.d.ts.DatePickerComponent.html(2,7): : Property 'backgroudStyle' does not exist on type 'DatePickerComponent'. Did you mean 'backgroundStyle'?`

In your /src/components/date-picker-component/date-picker-component.ts on lines 6 and 7 the backgroundStyle is misspelled with backgroudStyle (missing the 'n').

**Comment by write2sv** [comment]
Hi @jphornor , Thanks for opening this issue. I just fixed this. Please try now.

**Comment by jphornor** [comment]
Thank you, sir!
