### ISSUE TITLE
Is it possible to pass dates which can be disabled or vice versa?

### ISSUE THREAD

**Issue by Sireini** [write2sv/ionic4-date-picker#3]
I want to create a calendar where I get input from database with dates which are available. Is it possible to pass those dates to the calendar component so I can disable certain days in a month?

And it will be very nice if you can change the padding of overall columns.

Great job so far!

**Comment by write2sv** [comment]
Hi @Sireini, 
1. When you say you are going to provide dates as input, With in that startDate and endDate (If they are provided) I will make sure the component only allows the provided dates to be selected. I am thinking I will call this input validDates. I will leave up to you to make sure these validDates fall under startDate and endDate if you are providing them.

2. I think I should be able to provide a custom styling param for padding of overall columns. I do not see any issue with it.

**Comment by write2sv** [comment]
I have added validDate. This addresses no:1.

For no: 2 when I think about it now I would rather not touch it as I better leave it to the Grid to handle the padding. If you insist I will do it ;)

I am closing this ticket. Feel free to open another one!
