### ISSUE TITLE
Custom styling for specific arrays of dates

### ISSUE THREAD

**Issue by jakecurrant** [write2sv/ionic4-date-picker#4]
Hi,

Reasonably new to development in ionic 4, looking for a way to customise the calendar such that it takes arrays of dates and edits background colour for those dates only, though I don't see a specific styling option for that?

Any help would be appreciated, thanks.

**Comment by write2sv** [comment]
Hi @jakecurrant ,

May I know what the use case is here. Why do you want those dates to have a different color. Is it because they are the only available dates to select?

Thanks,
Surya.

**Comment by jakecurrant** [comment]
Hi, 

I'm developing an app for users to keep track of activities they carry out over an allotted period, and want to distinguish days with complete data, from days with incomplete or partial data.

I did look at the invalid date functions, but it did not fulfil the role I require, which would simply be to edit the style of specific dates, similar to how the background style of the selected date is set.

Thanks,
Jake

**Comment by write2sv** [comment]
Thats nice. Good luck with your app!

Yes, that should be possible. Let me see what I can do here.

Thanks,
Surya.

**Comment by write2sv** [comment]
Hi @jakecurrant, I have added a new input dateStyles.

[dateStyles] - An Java dictionary representing style (value) for each date in YYYY-MM-DD (key in ISO). 

**For eg in your component:** dateStyles = { '2019-04-10': {'background-color': 'red'}, '2019-04-09': {'background-color': 'green'}, '2019-04-08': {'background-color': 'blue'}, }; 

_Hint: You can use toDate().toISOString().slice(0,10) on your Date object to quickly get the key._

**And in your component's html:**
<ionic-calendar-date-picker [dateStyles]="dateStyles" (onSelect)="dateSelected($event)"></ionic-calendar-date-picker>	

Let me know if you see any issues while using this.
