### ISSUE TITLE
Ionic 5 & Angular 9 support

### ISSUE THREAD

**Issue by eduboxgithub** [write2sv/ionic4-date-picker#9]
This current version doesn't support the latest version of ionic and angular

**Comment by galsilb** [comment]
Any updates on that?

**Comment by hatsantos** [comment]
I also need to upgrade an app to Angular 9 and Ionic 5 ang I'm getting errors.

**Comment by galsilb** [comment]
If you can, test this fix in you app as well. Its working on my setup anyway.

**Comment by write2sv** [comment]
Thank you very much @galsilb for your contribution

**Comment by galsilb** [comment]
Cheers :) @write2sv
